import matplotlib.pyplot as plt

def plot_products_sold(df):
    """Bar chart for products sold by each salesperson."""
    plt.bar(df['Salesperson'], df['Products_Sold'], color='skyblue')
    plt.title('Products Sold by Salesperson')
    plt.xlabel('Salesperson')
    plt.ylabel('Products Sold')
    plt.show()

def plot_revenue(df):
    """Line plot for revenue generated by each salesperson."""
    plt.plot(df['Salesperson'], df['Revenue'], marker='o', linestyle='--', color='g')
    plt.title('Revenue Generated by Salesperson')
    plt.xlabel('Salesperson')
    plt.ylabel('Revenue')
    plt.show()

def plot_target_summary(target_count):
    """Pie chart to show target achievement summary."""
    target_count.plot.pie(autopct='%1.1f%%', colors=['lightgreen', 'lightcoral'])
    plt.title('Sales Target Met')
    plt.ylabel('')
    plt.show()
